name: Build and release giang-nguyen-portfolio-cms

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: ~/.yarn/cache
                  key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-node-

            - name: Install Dependencies
              run: yarn install

            - name: Run Build (This will generate dist/ and build/)
              run: yarn build

            - name: Create Release Archive
              run: tar -czvf release.tar.gz dist/ build/

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
              with:
                  tag_name: release-${{ github.sha }}
                  release_name: Release ${{ github.sha }}
                  draft: false
                  prerelease: false

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./release.tar.gz
                  asset_name: release.tar.gz
                  asset_content_type: application/gzip
